# coding: utf-8
Vagrant.configure(2) do |config|
#Boxの指定
  config.vm.box = "pyama/wdb-ruby-2.3"

  config.vm.define :proxy_1 do |c|
    c.vm.hostname = "proxy-1.wdp4.com"
#VMに設定するIPアドレスを指定
    c.vm.network "private_network", ip: "192.168.80.10"
#NFSを利用しコンテンツを連携
    c.vm.synced_folder "/Users/saki/ruby_project/todo/todoApp",
    "/var/www/todo", nfs: true
#VMのスペックを指定
    c.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", 512]
      vbox.customize ["modifyvm", :id, "--cpus", 1]
    end
    c.vm.provision :itamae do |itamae|
      itamae.sudo = true
      itamae.recipes = ['./nginx.rb']
    end
  end
end
